import React from 'react';
import Image from 'next/image';
import { useUser } from '@auth0/nextjs-auth0/client';
import Head from 'next/head';
import { Button, NavbarBrand } from 'reactstrap';

// Styles
const navbarStyle = {
  backgroundColor: '#D1C2D9',
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'center',
  padding: '10px 20px',
};

const navMenuStyle = {
  listStyleType: 'none',
  margin: 0,
  padding: 0,
  display: 'flex',
  gap: '20px',
};

const navItemStyle = {
  cursor: 'pointer',
};

const logoutButtonStyle = {
  backgroundColor: '#6C3483',
  color: '#fff',
  border: 'none',
  padding: '10px 20px',
  cursor: 'pointer',
};

// Navbar component
const CustomNavbar = () => {
  const { user } = useUser();

  return (
    <nav style={navbarStyle}>
      <Image src="/images/Kaan_Massage.jpg" alt="Ka'an Massage and Beauty" width={160} height={80} layout="intrinsic" />
      <ul style={navMenuStyle}>
        <li style={navItemStyle}>HOME</li>
        <li style={navItemStyle}>ABOUT</li>
        <li style={navItemStyle}>RATES + SERVICES</li>
        <li style={navItemStyle}>GIFT CERTIFICATES</li>
        <li style={navItemStyle}>HOURS</li>
        <li style={navItemStyle}>CONTACT US</li>
      </ul>
      {user && <button onClick={() => window.location.href = '/api/auth/logout'} style={logoutButtonStyle}>LOG OUT</button>}
    </nav>
  );
};

// Home page component
const Home = () => {
  const { user } = useUser();

  const fullPageStyle = {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100vh',
    background: 'linear-gradient(to bottom, #E8DEED 50%, #D1C2D9 50%)',
  };

  const headerTextStyle = {
    color: '#6C3483',
    fontSize: '2rem',
    fontWeight: 'bold',
    textAlign: 'center',
    margin: '0',
  };

  const subTextStyle = {
    color: '#6C3483',
    fontSize: '1rem',
    textAlign: 'center',
    marginTop: '0.5rem',
  };

  const loginButtonStyle = {
    backgroundColor: '#6C3483',
    borderColor: '#6C3483',
    color: '#fff',
    padding: '15px 30px',
    fontSize: '1rem',
    borderRadius: '20px',
    marginTop: '2rem',
  };

  const footerTextStyle = {
    fontSize: '1.25rem',
    color: '#6C3483',
    position: 'absolute',
    bottom: '1rem',
    textAlign: 'center',
    width: '100%',
  };

  return (
    <>
      <Head>
        <title>Calendar App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomNavbar />
      <div style={fullPageStyle}>
        <h1 style={headerTextStyle}>Welcome to Your Calendar</h1>
        {user && (
          <>
            <img
              src={user.picture}
              alt="Profile"
              className="nav-user-profile rounded-circle"
              width="50"
              height="50"
            />
            <p>Hello, {user.name}</p>
            <a href="/booking" className="btn btn-primary">Go create a booking</a>
        
          </>
        )}
        <div style={footerTextStyle}>
          <NavbarBrand href="/">Calendar App</NavbarBrand>
        </div>
      </div>
    </>
  );
};

export default Home;
