import '../styles/globals.css';
import { Provider } from 'react-redux';
import { Store } from 'redux';
import UserProvider from 'components/UserProvider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ Component, pageProps }) {
 return (
    <html lang="en">
      <Provider store={store}>
      <Component {...pageProps} />
      </Provider>
    </html>
  )
}